system_logger:
  level: debug
  destination: stdout
  formatter: text

pep:
  ssl_cert: cert.pem
  ssl_cert_key: key.pem
  ca_certs_to_verify_client_certs:
    - ca.pem

pe:
  target_addr: "https://pe.example.com:8080"